### ISSUE TITLE
建立favorite route

### ISSUE THREAD

**Issue by kmexin** [fontend-team4/TriPuzzle_Backend#5]
**要和提摩西拿places的資料**

功能：
1. 能列出使用者的收藏項目
2. 以使用者身分新增收藏項目
3. 以使用者身分刪除收藏項目

**Comment by LindseyL222** [comment]
1. 假地點資料、user的ID找已登入的useId
![地點假資料](https://github.com/user-attachments/assets/8e3f460c-484b-4c17-8162-4d49278e3697)
![螢幕擷取畫面 2024-12-14 224441](https://github.com/user-attachments/assets/0526466b-1d8c-4a74-b403-95b7d398dcce)


2.  試做的時候用user1，截圖示範用user2；確認有登入內容。
![user假資料](https://github.com/user-attachments/assets/389a117d-ee86-486c-b35d-02cf67a0e4f3)
![登入Token](https://github.com/user-attachments/assets/56ede216-a659-4319-9eba-6280b6147644)


3. 收藏地點成功並加入table
![成功新增](https://github.com/user-attachments/assets/a45544fc-4c38-4879-a819-0abb3233713b)
![資料庫成功新增](https://github.com/user-attachments/assets/672383ba-d885-4bea-9e28-a4f3129641db)


4. 移除地點成功並從table移除
![成功移除](https://github.com/user-attachments/assets/b3082bca-35dc-4a65-8751-f3ec19d991d9)
![資料庫成功移除](https://github.com/user-attachments/assets/9ac29203-22c7-433a-a5fe-3cf4da55e17a)
